### ISSUE TITLE
Autowiring broken when loading class via shared interface

### ISSUE THREAD

**Issue by carbontwelve** [thephpleague/container#119]
I have a `KernelInterface` class which is implemented by various different user definable `Kernel` classes with the default being a `DefaultKernel` class; this is handled by the following code:

```php
if (file_exists($kernelPath)){
    include $kernelPath;
    $container->share(KernelInterface::class, $configuration->get('kernel', DefaultKernel::class));
}else{
    $container->share(KernelInterface::class, DefaultKernel::class);
}

/** @var KernelInterface $kernel */
$kernel = $container->get(KernelInterface::class);
$kernel->boot();
```

The KernelInterface is as follows:

```php
interface KernelInterface
{
    public function boot();
}
```

The DefaultKernel is as follows:

```php
class DefaultKernel implements KernelInterface
{
    /**
     * @var Project
     */
    private $project;

    /**
     * DefaultKernel constructor.
     * @param Project $project
     */
    public function __construct(Project $project)
    {
        $this->project= $project;
    }

    public function boot()
    {
        // ...
    }
}
```
If the implementation of KernelInterface doesn't have a `__construct` it works fine and the kernel's boot method will be executed; however with the `__construct` I get the following error message:

```
Catchable fatal error: Argument 1 passed to App\Modules\Kernel\DefaultKernel::__construct() must be an instance of App\Project, none given
```

The only way I can get `Project` to be autowired is if I use the class name directly `$kernel = $container->get(DefaultKernel::class);` instead of via the interface.

I have auto-wiring enabled via the use of the `League\Container\ReflectionContainer` delegate. 

Is this a bug or am I doing something wrong?

**Comment by philipobenito** [comment]
Autowiring doesn't work with services that have been registered, this is intended behaviour because of what people perceive to be happening. 

Autowiring is there purely to quickly prototype and is supposed to be swapped out and have your dependencies defined to create a proper dependency map.

Does every `Kernel` class accept the same dependency of `App\Project`?

**Comment by carbontwelve** [comment]
> Does every Kernel class accept the same dependency of App\Project?

My Kernel class is dynamic, the end developer may have different requirements and just need say the Configuration class injected into their Kernel. I guess I should have the Container injected on construct as the end developer may wish to add their own service providers and what-not; which is kind of the idea we had behind the Kernel class.

> Is this a bug or am I doing something wrong?

If this is intended behavior then I must be doing something wrong :) Most of the time I configure constructor injections implicitly; however when you have an interface it is entirely possible that two classes that implement the same interface may require different things on construct - in which case auto-wiring is useful - if not slightly grubby.

**Comment by philipobenito** [comment]
The problem is that auto-wiring does not look at what has been registered with the container and assumes it is building the object from scratch with no prior information, this is the part that is intentional as before, when I mixed the two, it caused a lot of confusion with developers who didn't know why it was or was not working.

In short, auto-wiring does not work with interfaces, you have to pull a concrete implementation from the container for it to attempt to auto-wire (as interfaces do not have constructors and the argument sent to `Container::get` is all it has to work with).

**Comment by carbontwelve** [comment]
>  ...it caused a lot of confusion with developers who didn't know why it was or was not working...
Magic code tends to do that :) I'm not knocking your choice to limit the auto-wiring magic to assuming it's building the object from scratch with no prior information. Coming from working with Laravels DI and it's absurd level of built in magic, I assumed all auto-wiring operated the same and it confused me why it wouldn't work.

I have two options, I could either implicitly inject the container into every instance of Kernel thus allowing the end developer to interact with the container directly; or I could write my own modified version of `ReflectionContainer` that does the absurd magic that I am looking for :) 

Either way this isn't a problem with the Container so I am closing this issue. Thank you for your help.
