### ISSUE TITLE
Most performant and memory-efficent usage

### ISSUE THREAD

**Issue by texelate** [thephpleague/container#141]
Hi,

Love the container, great work!

I am using v2 and the docs say:

> The most performant way to use Container is to use factory closures/anonymous functions to build your objects. 

Why is it more performant to pass functions instead of class names? 

Also, I have about 200 classes in total in my framework and I notice if I register them all using `add` or `share` — by passing class names and references as opposed to closures as above — I notice the memory usage jumps up from ~2MB to ~4.5MB. I'm confused as to why this is because the objects don't actually get created until `get` is called, right?

In a typical page view I'd say only about 50 of the 200 classes get used. I know 5MB is not a huge amount of memory usage but I prefer to keep it as low as possible. I was going to make a class to call `add` and `share` on the fly through a simple lookup associative array but thought I'd check first if there was a built-in way to do this.

Until a couple of days ago I'd never used a DIC so don't know if this is fighting against it, if I'm using it wrong or if increased memory usage is par for the course.

Thank you!

**Comment by philipobenito** [comment]
Hi Tim,

The “more performant” part of the docs is probably slightly outdated and although still true (because using a closure/anon function requires the container to do less as it just invokes the function), it’s less true now because one method became less performant, and one more performant in later versions (negligible amounts).

As for your other question, I’d say there probably isn’t a right or wrong. However small, you take a hit when using a container but it’s worth it for the benefits you gain.

I’ve seen people doing funky things like mapping routes to sets of container “registrations” within middleware and stuff like that, personally I group them in to service providers as they’re lazy loaded, so everything needed by a route in a service provider (duplication is okay because in most instances registrations will only happen once as not all service providers are run, and in the rare cases where they are, they’ll just be overridden), then when the controller is pulled from the container it’ll register everything else.

I’ve also been working on a way to build a “compiled” container which will essentially be a caching mechanism that you use in production.

Hope that helps, feel free to ask any other questions.

Phil

**Comment by texelate** [comment]
Hi Phil,

Thanks for the fast reply!

I'm really happy with how it's set up. I do some bootstrapping but, because the object graph is fully defined in the config, once all the bootstrapping is done I simply load the controller and call a function based on the route and the container then works everything out! I love that. I was using a registry-type pattern before but it was becoming difficult to maintain.

My confusion really is why registering an object seems to use ~15k of memory. I'm not questioning that is shouldn't, I guess I am more curious as to _why_ it does as isn't it just storing the relationship rather than the object itself?

> I group them in to service providers as they’re lazy loaded, so everything needed by a route in a service provider

What do you mean that service providers are lazy-loaded? I only ask because that implies if you _don't_ use service providers then they're _not_ lazy-loaded. I assumed that nothing is actually instantiated until you call `get` — in which case it is very difficult to actually use the container in an inefficient way! I also don't yet understand the benefits of service providers in this context. Why not just work on an individual object level since the container will manage the dependencies for you? Like in my case I request a few objects to get things going but once I create the controller, that's it!

I already have a class that manages the container in that it loads the full object graph in from a PHP file and `add`s and `share`s everything on one go. I'm thinking it would be pretty easy to register them only when they are requested for the first time just to save a bit of memory. Or is there a better way?

Thanks again! It's been an educational experience to start using this.

**Comment by philipobenito** [comment]
Hey,

So the memory usage is because an object is instantiated that defines the object you are registering and everything the container needs to know, dependencies etc. This is a design choice within the container to solidify data and make it less prone to user error etc.

I’ll try and explain what I mean about lazy loading. When you add a class to the container, it isn’t instantiated until it’s needed, however, as mentioned above, a very lightweight descriptive object is. When you use a service provider, it creates those descriptive objects, and therefore the dependency map lazily too, so they won’t be defined until they’re requested. What this means in practice is that if you have 200 objects for your app but a particular operation/request/route only needs 40-50, you can ensure the container only actually defines what you need for that operation. I hope that makes sense, if not then I’ll try to provide a better example when I’m at a computer.

**Comment by texelate** [comment]
Hi Phil,

Thanks for that, I understand now.

With that in mind, would an easy way to lazy load be to simply wrap the container in a static class and then wrap everything in a function?
```
$container->add('foo', '\Foo\Bar')->withArgument('argument');
```

Becomes:

```
$container->add('foo', function() {

    return Container::$container->add('foo', '\Foo\Bar')->withArgument('argument')->get('foo');

});
```
Or would that be inefficient if you call it more than once since it would get redefined? I'm thinking making a service provider per route would be too complex for me and that maybe my original idea of using a lookup array would be simpler and more performant.

Thanks!

**Comment by texelate** [comment]
Hi Phil,

Thanks, I understand now!

I'm still unsure when I'd user a service provider though since that seems like it would require a fair bit of additional code on top of my object graph because I would need to manually work out what any given route would need.

I think I'll roll my own simple lazy-loading. I'll get this done early next week and post my findings before closing this if that's okay — just in case I can post something that is useful to anyone else.

**Comment by texelate** [comment]
Hi Phil,

I have given up on the lazy loading idea. I realised on my local machine I didn't have OPcache enabled and was comparing its usage to a site that _did_ have Opcache enabled. So actually, while registering objects does increase the memory usage, it's negligible.

I'll close this now.

Thanks again.

**Comment by texelate** [comment]
Having played around with this more I can confirm (YMMV):

- Setting up objects and _not_ using them _does_ use memory; for me it was about 1MB per 100 objects
- Using OPcache reduces this but there is still noticeable memory increase
- I also took a performance hit of of abut 20ms per request per 100 objects set up
- As the docs say the most performant way is to pass closures
- I just wanted to use my object graph PHP file as is so I rolled my own lazy loading*; it took me a few hours but I have reduced the number of objects set up from 200 to about 30 per and the execution time and memory usage have both gone down significantly

_*Each time an object is requested I hold an array for those that have already been set up. If not set up I work up through the dependencies and create a list of objects to set up and then run `add` and `share` then return the object. Any future requests are then “cached”, that is, the objects are just returned directly from the container.

The other cool thing is now in my logging I can se a list of every object used for that request.

Why didn't I just use closures? Well, I had already set up my object graph as a PHP associative array. Plus, I inject runtime config and it was just easier this way._

I hope that helps someone.

Now it's set up, it's so easy to manage. :-)

**Comment by philipobenito** [comment]
That's good to know, thanks for sharing your experience with it. However, that is essentially what Service Providers already do, so maybe I should be padding out the docs a little more where that is concerned.

I used to have some benchmarks comparing to other containers, not sure what I did with them in the end.
