### ISSUE TITLE
What is the difference between Callable and Closure definition?

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/container#2]
I can't see any difference other than a few lines of different formatting a different type hint. Does it make any sense?

**Comment by philipobenito** [comment]
`ClosureDefinition` doesn't handle arguments at all, they're simply aimed at being factories, so we're only dealing with the return. 

`CallableDefinition` is a different concept allowing us to actually invoke a callable with either pre-defined or auto resolved arguments. The main reason this was accepted as a PR is because it gives us scope in league/route to only define our dependencies per Controller method, not just at class level. Does that make sense? So `ClosureDefinition` only really cares about a return value, no input, mainly used to return a class (it's just faster than using `withArgument` etc, but only really deals with classes). `CallableDefinition` deals with the method/function instead, no knowledge of class dependencies needed.

**Comment by sagikazarmark** [comment]
But the two classes are identical. Same parents, same function calls. The only difference is a property name, a type hint, and instead of inline function call, it is saved in a variable.

**Comment by philipobenito** [comment]
They are right now, but the road map is to allow for knowledge of variadics or secondary arguments for the callable. This way a controller can be invoked with auto-resolved dependencies but also have secondary arguments (such as parts of a wildcard route) passed in.

**Comment by philipobenito** [comment]
The similarities here mean that it is probably a good idea to merge the two types of definition and proxy the `callable` functionality through... Thanks for pointing this out, I'll reference a PR when complete.

**Comment by philipobenito** [comment]
Happy with #5 ?

**Comment by sagikazarmark** [comment]
Great :+1:

**Comment by philipobenito** [comment]
I'll close this and pick it up as part of the milestone. Thanks :+1:
