### ISSUE TITLE
Aliased classes's constructor arguments not injected?

### ISSUE THREAD

**Issue by Anahkiasen** [thephpleague/container#23]
Take the following code:

```php
class Foo {}

class Bar {
    public function __construct(Foo $foo) {}
}

$container = new Container();
$container->add('some.alias', 'Bar');

dump($container->get('Bar')); // Will work
dump($container->get('some.alias')); // Argument 1 passed to Bar::__construct() must be an instance of Foo, none given
```

Is there no way to have aliased services be auto-resolved, without having to specify all their constructor arguments manually like this:

```php
$container->add('some.alias', 'Bar')->withArgument('Foo');
```

**Comment by philipobenito** [comment]
Unfortunately not, the reason for this is that auto resolution uses reflection and reflection is slow. 

Any defined objects will never use reflection so that the user has a clear choice between the two ensuring that there is no unknown overhead on the application.

This alias doesn't actually have any bearing on this at all, what is actually happening in your example when you call `get('Bar`)` is that the container is just resolving the class `Bar`, it has no knowledge that it is registered within the container as a different alias.

I am planning some command line tools to allow you to just use auto resolution throughout your development cycle and then generate a compiled container for use in production but this is a while off yet.

I hope that helps.
