### ISSUE TITLE
Have InflectorAggregate::inflect() also look at traits?

### ISSUE THREAD

**Issue by Potherca** [thephpleague/container#99]
When the InflectorAggregate inflects on an object, it doesn't look at traits, only interfaces.

I was wondering if it would be worth the effort of adding support for traits?

Arguments against such a thing could be that traits _shouldn't_ be used for inflection or that adding extra code (and thus extra complexity) isn't desired.

So before opening a PR to that effect, I thought it might be wise to post this question first.

**Comment by philipobenito** [comment]
Because traits do not have type I don't feel like this would be a good addition for now. It would only be a one liner so it's not complexity that is the problem, it's more that inflectors inflect on a type, allowing inflection on a class that uses a trait blurs the line of that functionality for me.

Have you seen this RFC? https://wiki.php.net/rfc/traits-with-interfaces, it may be of some interest to you.
